// Generated by gencpp from file metal_line_follower/beginOpMsg.msg
// DO NOT EDIT!


#ifndef METAL_LINE_FOLLOWER_MESSAGE_BEGINOPMSG_H
#define METAL_LINE_FOLLOWER_MESSAGE_BEGINOPMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace metal_line_follower
{
template <class ContainerAllocator>
struct beginOpMsg_
{
  typedef beginOpMsg_<ContainerAllocator> Type;

  beginOpMsg_()
    : enableOperation(false)  {
    }
  beginOpMsg_(const ContainerAllocator& _alloc)
    : enableOperation(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enableOperation_type;
  _enableOperation_type enableOperation;




  typedef boost::shared_ptr< ::metal_line_follower::beginOpMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metal_line_follower::beginOpMsg_<ContainerAllocator> const> ConstPtr;

}; // struct beginOpMsg_

typedef ::metal_line_follower::beginOpMsg_<std::allocator<void> > beginOpMsg;

typedef boost::shared_ptr< ::metal_line_follower::beginOpMsg > beginOpMsgPtr;
typedef boost::shared_ptr< ::metal_line_follower::beginOpMsg const> beginOpMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metal_line_follower::beginOpMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace metal_line_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'metal_line_follower': ['/home/farhan/catkin_ws/src/metal_line_follower/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metal_line_follower::beginOpMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_line_follower::beginOpMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_line_follower::beginOpMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71ee0ed5e8ee97a464b9e21ee3b05a3e";
  }

  static const char* value(const ::metal_line_follower::beginOpMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71ee0ed5e8ee97a4ULL;
  static const uint64_t static_value2 = 0x64b9e21ee3b05a3eULL;
};

template<class ContainerAllocator>
struct DataType< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metal_line_follower/beginOpMsg";
  }

  static const char* value(const ::metal_line_follower::beginOpMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enableOperation\n\
";
  }

  static const char* value(const ::metal_line_follower::beginOpMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enableOperation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct beginOpMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metal_line_follower::beginOpMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metal_line_follower::beginOpMsg_<ContainerAllocator>& v)
  {
    s << indent << "enableOperation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableOperation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // METAL_LINE_FOLLOWER_MESSAGE_BEGINOPMSG_H
