// Generated by gencpp from file metal_line_follower/proximityMsg.msg
// DO NOT EDIT!


#ifndef METAL_LINE_FOLLOWER_MESSAGE_PROXIMITYMSG_H
#define METAL_LINE_FOLLOWER_MESSAGE_PROXIMITYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace metal_line_follower
{
template <class ContainerAllocator>
struct proximityMsg_
{
  typedef proximityMsg_<ContainerAllocator> Type;

  proximityMsg_()
    : sender()
    , leftSensor(false)
    , centerSensor(false)
    , rightSensor(false)  {
    }
  proximityMsg_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , leftSensor(false)
    , centerSensor(false)
    , rightSensor(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef uint8_t _leftSensor_type;
  _leftSensor_type leftSensor;

   typedef uint8_t _centerSensor_type;
  _centerSensor_type centerSensor;

   typedef uint8_t _rightSensor_type;
  _rightSensor_type rightSensor;




  typedef boost::shared_ptr< ::metal_line_follower::proximityMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metal_line_follower::proximityMsg_<ContainerAllocator> const> ConstPtr;

}; // struct proximityMsg_

typedef ::metal_line_follower::proximityMsg_<std::allocator<void> > proximityMsg;

typedef boost::shared_ptr< ::metal_line_follower::proximityMsg > proximityMsgPtr;
typedef boost::shared_ptr< ::metal_line_follower::proximityMsg const> proximityMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metal_line_follower::proximityMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metal_line_follower::proximityMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace metal_line_follower

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'metal_line_follower': ['/home/farhan/catkin_ws/src/metal_line_follower/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metal_line_follower::proximityMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metal_line_follower::proximityMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metal_line_follower::proximityMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af11528ee9c2394e81b2d19dd1d4bc01";
  }

  static const char* value(const ::metal_line_follower::proximityMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf11528ee9c2394eULL;
  static const uint64_t static_value2 = 0x81b2d19dd1d4bc01ULL;
};

template<class ContainerAllocator>
struct DataType< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metal_line_follower/proximityMsg";
  }

  static const char* value(const ::metal_line_follower::proximityMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n\
bool leftSensor\n\
bool centerSensor\n\
bool rightSensor\n\
\n\
";
  }

  static const char* value(const ::metal_line_follower::proximityMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.leftSensor);
      stream.next(m.centerSensor);
      stream.next(m.rightSensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct proximityMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metal_line_follower::proximityMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metal_line_follower::proximityMsg_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "leftSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leftSensor);
    s << indent << "centerSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.centerSensor);
    s << indent << "rightSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rightSensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // METAL_LINE_FOLLOWER_MESSAGE_PROXIMITYMSG_H
